import { Geist, Geist_Mono, Orbitron } from "next/font/google";
import "./globals.css";
import { CartProvider } from "../context/CartContext";

const orbitron = Orbitron({
    subsets: ["latin"],
    variable: "--font-orbitron-family",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
 return (
    <html
        lang="en"
        className={`${geistSans.variable} ${geistMono.variable} ${orbitron.variable} h-full antialiased`}
    >
        <body className="min-h-full flex flex-col">
            <CartProvider>
                {children}
            </CartProvider>
        </body>
    </html>
);
}
